package com.example.todo;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.widget.ArrayAdapter;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;
import android.view.KeyEvent;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import androidx.databinding.BaseObservable;
import androidx.databinding.Bindable;

import com.google.android.material.snackbar.Snackbar;


public class TaskListActivity extends AppCompatActivity implements TaskListAdapter.TaskSelectionListener {

    private static final String BUNDLE_KEY_PLACES = "BUNDLE_KEY_PLACES";

    //private ActivityTaskListBinding binding;
    private TaskListAdapter adapter;

    private ArrayList<Task> tasks;
    private TaskRepository repository;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //binding = ActivityTaskListBinding.inflate(getLayoutInflater());
        //setContentView(binding.getRoot());

        // Define reaction to events on edit text field and button
        // a) for events generated by the add button
        findViewById(R.id.addTaskButton).setOnClickListener(v -> addNewTask());
        // b) for events dispatched from the keyboard to the EditText
        /*
        binding.editTextTaskName.setOnKeyListener((v, keyCode, event) -> {
            if (event.getAction() == KeyEvent.ACTION_DOWN) {
                if (keyCode == KeyEvent.KEYCODE_ENTER) {
                    addNewTask();
                    return true;
                }
            }
            return false;
        });*/

        if (savedInstanceState == null) {
            tasks = new ArrayList<>(Arrays.asList(new Task("Groceries"), new Task("Homework"), new Task("Make an App")));
        } else {
            tasks = (ArrayList<Task>) repository.loadTasks();
        }

        // RecyclerView
        RecyclerView recyclerView = findViewById(R.id.taskRecycler);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        adapter = new TaskListAdapter(this);
        adapter.setTasks(tasks);
        recyclerView.setAdapter(adapter);
    }

    public void addNewTask() {

        //String taskName = binding.editTextTaskName.getText().toString();
        Snackbar.make(findViewById(android.R.id.content).getRootView(), "New Task has been added! ", Snackbar.LENGTH_SHORT).show();
        //tasks.add(new Task(placeName));
        //adapter.notifyItemInserted(tasks.size()-1);
        //binding.editTextTaskName.setText("");
    }

    /*@Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        outState.putParcelableArrayList(BUNDLE_KEY_PLACES, tasks);

        super.onSaveInstanceState(outState);
    }*/

    /*
     * Implementation of interface PlaceSelectionListener
     */
    @Override
    public void onTaskSelected(Task task) {
        Intent intent = new Intent(this, TaskDetailActivity.class);
        intent.putExtra(TaskDetailActivity.EXTRA_TASK_NAME, task.getShortName());
        startActivity(intent);

        // Alternative intent: google for the place
//        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.google.de/search?q=" + place.getName()));
//        startActivity(intent);

//        Alternative intent: Show map based on address
//        Uri location = Uri.parse("geo:0,0?q="+place.getName());
//        Intent mapIntent = new Intent(Intent.ACTION_VIEW, location);
//        startActivity(mapIntent);
    }
}